[incoming]
exten => 1000,1,Answer()
 same => n,Playback(hello-sir-this-is-automated-call)
 same => n,Playback(please-tell-ur-urgency)

 same => n,Record(/tmp/input.wav,5)

 same => n,System(curl -X POST https://callman.onrender.com/process -H "Content-Type: application/json" -d '{"text":"urgent"}')

 same => n,Playback(vm-goodbye)
 same => n,Hangup()
